version: '2'

services:
  proyecto:
    container_name: servicios
    build: ./horariosfic
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - socket
      
  socket:
    container_name: socket
    build: ./socket
    ports:
      - 3000:5000
    volumes:
      - ./socket:/app